spring:
  r2dbc:
    url: r2dbc:pool:postgres://localhost:5434/postgres
    username: postgres
    password: postgres
  flyway:
    url: jdbc:postgresql://localhost:5434/postgres
    locations: classpath:db/migration
    user: postgres
    password: postgres
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/hypercore
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
      client:
        registration:
          keycloak:
            client-id: hypercore
            client-secret: JNB8wDVT8pijXIojIZjQjdyayZoSVeKX

logging:
  level:
    io.r2dbc.postgresql.QUERY: DEBUG
    io.r2dbc.postgresql.PARAM: DEBUG
server:
  port: 8081

keycloak:
  server-url: http://localhost:8080
  realm: hypercore
  username: shevts0v1sasha
  password: password