spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/hypercore
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
      client:
        registration:
          keycloak:
            client-id: hypercore
            client-secret: JNB8wDVT8pijXIojIZjQjdyayZoSVeKX


server:
  port: 8081

keycloak:
  server-url: http://localhost:8080
  realm: hypercore
  username: shevts0v1sasha
  password: password